// Para elegir un fragmento concreto cambia start (segundos). También puedes
// indicar end y volume. Ejemplos: 0:47 = 47; 1:12.5 = 72.5.
const openingTrack={audio:'00-opening.mp3',start:0,end:null,volume:.72};
const memories=[
{photo:'foto6.jpg',quote:'Somosh Pescadosh',comment:'Muack muack muack',song:'Kiss Me Thru The Phone — Soulja Boy ft. Sammie',audio:'01-kiss-me.mp3',start:50,end:null,volume:.72},
{photo:'foto2.jpg',quote:'No sé cómo lo hice, solo presioné los botones.',comment:'De la nada sacaba una nave espacial que tiraba un rayo y me ganaba.',song:'Uptown Girl — Billy Joel',audio:'02-uptown-girl.mp3',start:0,end:null,volume:.72},
{photo:'foto12.jpg',quote:'Puta madre Emiliano.',comment:'No había entendido la referencia.',song:'Drive By — Train',audio:'03-drive-by.mp3',start:32,end:null,volume:.72},
{photo:'foto9.jpg',quote:'I contribute to society...',comment:'Me encanta cuando te emocionas por aprender algo.',song:'Mon Amour (Remix) — Aitana & Zzoilo',audio:'04-mon-amour.mp3',start:8,end:null,volume:.72},
{photo:'foto10.jpg',quote:'No, no ¿A dónde vas?',comment:'No te acuerdas, pero yo sí y fue hermoso.',song:'Encantadora — Yandel',audio:'05-encantadora.mp3',start:22,end:null,volume:.72},
{photo:'foto7.jpg',quote:'Nuestra cama, nuestro cuarto, nuestra casa...',comment:'Así es amor, quiero compartir todo contigo.',song:'Just The Two Of Us — Bill Withers',audio:'06-just-two.mp3',start:39,end:null,volume:.72},
{photo:'foto4.jpg',quote:'No tienes por qué hablar con otras mujeres.',comment:'Ay amor, la verdad es que solo hablo porque tengo qué, si pudiese me aislaría para solo hablar contigo, muack.',song:'Intocable — Aleks Syntek',audio:'07-intocable.mp3',start:135,end:null,volume:1,gain:2},
{photo:'foto11.jpg',quote:'Me encanta tu ropa, te voy a robar tu ropa.',comment:'Puedes tomar toda la que quieras, amor. Yo adoro verte con mi ropa.',song:'Snowman — Sia',audio:'08-snowman.mp3',start:32,end:null,volume:.72},
{photo:'foto1.jpg',quote:'Gerberas... son mis favoritas ¿Cómo lo supiste?',comment:'No lo sabía jiji, coincidencia del destino supongo.',song:'Somewhere Only We Know — Keane',audio:'09-somewhere.mp3',start:113,end:null,volume:.72},
{photo:'foto8.jpg',quote:'Me mentiste... yo sí quería ir contigo al centro.',comment:'Y me dolió muchísimo decirte que fueras a tu casa a estudiar. Pero era por un bien mayor, hacerte sentir amada.',song:'Duele El Amor — Aleks Syntek ft. Ana Torroja',audio:'10-duele.mp3',start:58,end:null,volume:1,gain:2},
{photo:'foto5.jpg',quote:'¿Confías en mí? Todo va a estar bien, tienes que respirar.',comment:'Desde ese día, supe que podría confiarte mi vida, todo estuvo bien, solo tuve que respirar. Esas palabras continúan en mi cabeza cada vez que me siento mal.',song:"I Don't Want to Miss a Thing — Aerosmith",audio:'11-miss-a-thing.mp3',start:62,end:null,volume:.72},
{photo:'foto3.png',quote:'Aunque nos distanciemos ¿Seremos novios?',comment:'Siempre que tú quieras, hasta el fin de los tiempos estaremos juntos.',song:'Goodbye My Lover — James Blunt',audio:'12-goodbye.mp3',start:51,end:null,volume:.72},
{photo:'foto13.jpg',quote:'Eres mi núcleo, eres mi centro.',comment:'Pensaste que no me acordaría, pero te presto mucha atención. No sé si lo dijiste por reflejo, pero la verdad es que sí representa cómo me siento por ti, quiero hacerte feliz.',song:'Abrázame Muy Fuerte — Juan Gabriel',audio:'13-abrazame.mp3',start:5,end:null,volume:.72}];
const DURATION=14000;let idx=0,firstRun=true,timer=null,currentAudio=0,currentTrackAudio=openingTrack.audio,audioContext=null,gainNodes=null;const $=s=>document.querySelector(s), scenes=['opening','intro','albumScene','finalScene'];
const audios=[$('#audioA'),$('#audioB')]; audios.forEach(a=>{a.volume=0;a.loop=false});
function show(id){scenes.forEach(x=>$('#'+x).classList.toggle('active',x===id))}
function setSoundState(on){const b=$('#soundToggle');b.classList.toggle('needs-audio',!on);b.classList.toggle('sound-on',on);b.querySelector('span').textContent=on?'Pausar música':'Activar sonido';b.setAttribute('aria-label',on?'Pausar música':'Activar sonido');b.title=on?'Pausar música':'Activar sonido'}
function ensureAudioGraph(){if(audioContext||location.protocol==='file:')return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audioContext=new AC();gainNodes=audios.map(a=>{const source=audioContext.createMediaElementSource(a),gain=audioContext.createGain();gain.gain.value=Number(a.dataset.gain||1);source.connect(gain).connect(audioContext.destination);return gain});audioContext.resume().catch(()=>{})}catch(e){audioContext=null;gainNodes=null}}
function applyGain(elementIndex,track){audios[elementIndex].dataset.gain=String(track.gain||1);if(gainNodes)gainNodes[elementIndex].gain.value=track.gain||1}
function playCurrentAudio(){const a=audios[currentAudio];a.muted=false;const result=a.play();if(result)result.then(()=>setSoundState(true)).catch(()=>setSoundState(false));return result}
function startOpeningMusic(){const a=audios[0];a.src='assets/audio/'+openingTrack.audio;a.volume=openingTrack.volume;a.muted=false;a.dataset.gain='1';a.onloadedmetadata=()=>{a.currentTime=openingTrack.start||0;const result=a.play();if(result)result.then(()=>setSoundState(true)).catch(()=>setSoundState(false))};a.load()}
function fadeAudio(track){const next=1-currentAudio,incoming=audios[next],outgoing=audios[currentAudio];const target=Math.min(1,track.volume??.72);currentTrackAudio=track.audio;applyGain(next,track);incoming.onloadedmetadata=()=>{incoming.currentTime=Math.min(track.start||0,Math.max(0,incoming.duration-.1));incoming.muted=false;const result=incoming.play();if(result)result.then(()=>setSoundState(true)).catch(()=>setSoundState(false))};incoming.ontimeupdate=()=>{if(track.end&&incoming.currentTime>=track.end)incoming.currentTime=track.start||0};incoming.src='assets/audio/'+track.audio;incoming.volume=0;incoming.load();let t=0;const iv=setInterval(()=>{t+=.04;incoming.volume=Math.min(target,t*target);outgoing.volume=Math.max(0,outgoing.volume-.04*target);if(t>=1){clearInterval(iv);outgoing.pause();currentAudio=next}},45)}
function flowerBurst(){const box=$('#petals');box.classList.add('bursting');for(let i=0;i<96;i++){const p=document.createElement('img');p.className='vector-flower';p.src='assets/images/flower-vector.png';p.alt='';p.style.left=(Math.random()*112-6)+'vw';p.style.top=(Math.random()*112-6)+'vh';p.style.setProperty('--size',(11+Math.random()*25)+'vmin');p.style.setProperty('--x',(Math.random()*90-45)+'vw');p.style.setProperty('--y',(Math.random()*90-45)+'vh');p.style.setProperty('--r',(Math.random()*540-270)+'deg');p.style.animationDelay=(Math.random()*.5)+'s';box.appendChild(p)}setTimeout(()=>{box.classList.remove('bursting');box.replaceChildren()},3900)}
$('#openBtn').onclick=()=>{playCurrentAudio();ensureAudioGraph();$('#envelope').classList.add('open');setTimeout(()=>flowerBurst(),450);setTimeout(()=>show('intro'),2350)};
$('#startBtn').onclick=()=>{show('albumScene');buildProgress();render(0,true)};
function buildProgress(){const p=$('#progress');p.innerHTML='';memories.forEach((_,i)=>{const s=document.createElement('div');s.className='segment';s.innerHTML='<div class="fill"></div>';s.onclick=()=>{if(!firstRun)go(i)};p.appendChild(s)})}
function render(i,initial=false){idx=i;const m=memories[i];$('#photo').src='assets/images/'+m.photo;$('#quote').textContent='“'+m.quote+'”';$('#comment').textContent=m.comment;$('#songName').textContent=m.song;$('#counter').textContent=(i+1)+' / '+memories.length;$('#leftDoodle').textContent=i===0?'Somosh Pescadosh':'Mey + Naim';document.querySelectorAll('.segment').forEach((s,n)=>{s.className='segment'+(n<i?' done':'')+(n===i?' active':'');s.style.setProperty('--duration',DURATION+'ms')});$('#prevBtn').disabled=firstRun||i===0;$('#nextBtn').disabled=firstRun||i===memories.length-1;fadeAudio(m);clearTimeout(timer);if(firstRun)timer=setTimeout(()=>{if(idx<memories.length-1)go(idx+1);else finishFirstRun()},DURATION)}
function go(n){if(n<0||n>=memories.length||$('#book').classList.contains('is-turning'))return;const book=$('#book');const direction=n>idx?'turn-next':'turn-prev';book.classList.add('is-turning',direction,'content-fade-out');setTimeout(()=>{render(n);book.classList.remove('content-fade-out');book.classList.add('content-fade-in')},520);setTimeout(()=>book.classList.remove('is-turning','turn-next','turn-prev','content-fade-in'),1080)}
function finishFirstRun(){firstRun=false;$('#lockText').textContent='Ahora este álbum es tuyo; recórrelo cuando quieras';$('#freeActions').hidden=false;$('#prevBtn').disabled=false;$('#nextBtn').disabled=true;setTimeout(showFinal,1200)}
function showFinal(){show('finalScene');if(currentTrackAudio!==memories[memories.length-1].audio)fadeAudio(memories[memories.length-1]);if(!$('#collage').children.length){['foto1.jpg','foto3.png','foto8.jpg','foto13.jpg'].forEach(f=>{const im=document.createElement('img');im.src='assets/images/'+f;$('#collage').appendChild(im)})}flowerBurst()}
function closeLetter(){clearTimeout(timer);show('opening');$('#envelope').classList.remove('open');fadeAudio(openingTrack)}
$('#prevBtn').onclick=()=>go(idx-1);$('#nextBtn').onclick=()=>idx===memories.length-1?showFinal():go(idx+1);$('#revisitBtn').onclick=()=>{show('albumScene');render(memories.length-1)};$('#closeLetterBtn').onclick=closeLetter;$('#goFinalBtn').onclick=showFinal;
const playlistTracksData=[{title:'Til The Last One Dies',artist:'Chris Young',audio:'00-opening.mp3'},...memories.map(m=>{const parts=m.song.split(' — ');return{title:parts[0],artist:parts.slice(1).join(' — '),audio:m.audio}})];
const playlistAudio=$('#playlistAudio');let playlistIndex=0;
function formatTime(seconds){if(!Number.isFinite(seconds))return'0:00';const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return m+':'+String(s).padStart(2,'0')}
function updatePlaylistButton(){const use=$('#playlistPlayUse');use.setAttribute('href',playlistAudio.paused?'#icon-play':'#icon-pause');$('#playlistPlayBtn').setAttribute('aria-label',playlistAudio.paused?'Reproducir':'Pausar')}
function selectPlaylistTrack(index,autoplay=false){playlistIndex=(index+playlistTracksData.length)%playlistTracksData.length;const track=playlistTracksData[playlistIndex];playlistAudio.src='assets/audio/'+track.audio;playlistAudio.load();$('#playlistTrackTitle').textContent=track.title;$('#playlistTrackArtist').textContent=track.artist;document.querySelectorAll('.track-list button').forEach((b,i)=>b.classList.toggle('active',i===playlistIndex));if(autoplay)playlistAudio.play().catch(()=>{});updatePlaylistButton()}
function buildPlaylist(){const list=$('#playlistTracks');if(list.children.length)return;playlistTracksData.forEach((track,i)=>{const li=document.createElement('li'),button=document.createElement('button');button.type='button';button.innerHTML='<span class="track-number">'+String(i+1).padStart(2,'0')+'</span><span class="track-copy"><strong></strong><small></small></span><svg class="icon"><use href="#icon-play"/></svg>';button.querySelector('strong').textContent=track.title;button.querySelector('small').textContent=track.artist;button.onclick=()=>selectPlaylistTrack(i,true);li.appendChild(button);list.appendChild(li)});selectPlaylistTrack(0)}
function openPlaylist(){audios.forEach(a=>a.pause());setSoundState(false);buildPlaylist();$('#playlistModal').hidden=false;document.body.classList.add('modal-open')}
function closePlaylist(){playlistAudio.pause();$('#playlistModal').hidden=true;document.body.classList.remove('modal-open');audios[currentAudio].play().then(()=>setSoundState(true)).catch(()=>setSoundState(false))}
$('#playlistBtn').onclick=openPlaylist;$('#closePlaylistBtn').onclick=closePlaylist;$('#playlistModal').onclick=e=>{if(e.target===$('#playlistModal'))closePlaylist()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#playlistModal').hidden)closePlaylist()});
$('#soundToggle').onclick=()=>{const playing=audios.some(a=>!a.paused);if(playing){audios.forEach(a=>a.pause());setSoundState(false)}else{playCurrentAudio();ensureAudioGraph()}};
$('#playlistPlayBtn').onclick=()=>{if(playlistAudio.paused)playlistAudio.play().catch(()=>{});else playlistAudio.pause();updatePlaylistButton()};
$('#playlistPrevBtn').onclick=()=>selectPlaylistTrack(playlistIndex-1,true);$('#playlistNextBtn').onclick=()=>selectPlaylistTrack(playlistIndex+1,true);
playlistAudio.addEventListener('play',updatePlaylistButton);playlistAudio.addEventListener('pause',updatePlaylistButton);playlistAudio.addEventListener('ended',()=>selectPlaylistTrack(playlistIndex+1,true));playlistAudio.addEventListener('loadedmetadata',()=>{$('#playlistDuration').textContent=formatTime(playlistAudio.duration)});playlistAudio.addEventListener('timeupdate',()=>{$('#playlistCurrentTime').textContent=formatTime(playlistAudio.currentTime);$('#playlistProgress').value=playlistAudio.duration?playlistAudio.currentTime/playlistAudio.duration*100:0});$('#playlistProgress').oninput=e=>{if(playlistAudio.duration)playlistAudio.currentTime=Number(e.target.value)/100*playlistAudio.duration};
// preload
memories.forEach(m=>{const i=new Image;i.src='assets/images/'+m.photo});
startOpeningMusic();
